### ISSUE TITLE
name 'clock' is not defined

### ISSUE THREAD

**Issue by LePetitNewbie** [rebyates/build_fpl_team#1]
Hi Rebekah
           Hope you are well. I wanted to ask if you could help me with an error I have encountered while running your code. It appears when I try to run the solver 

sol = lp.solve()

I get this error: name 'clock' is not defined

![image](https://user-images.githubusercontent.com/81279182/118506267-83c6dc00-b770-11eb-9ad2-79eab01d893e.png)

I have no experience with coding. All was going smoothly until this part. Let me know if you can help.

thanks for your time and your work
take care
Ol

**Comment by LePetitNewbie** [comment]
Hi Rebekah,
      Do not Worry about it. I was running an old version of Pulp and the upgrade did the trick.

Thanks for your work

Sorry about that.

Cheers

**Comment by rebyates** [comment]
Hey Ol,

I thought that that might be the case ☺️
I'll add the version used in my environment in a comment so others don't come across a similar issue.

Thanks,
Rebekah
